version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=your_secure_password
      - MYSQL_DATABASE=todo_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=your_secure_password
      - MYSQL_DATABASE=todo_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this in production

volumes:
  db_data:
  prometheus_data:
  grafana_data: