version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=your_secure_password
      - MYSQL_DATABASE=todo_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=your_secure_password
      - MYSQL_DATABASE=todo_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: